# Generated by Django 5.2.3 on 2025-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(default='app', max_length=20),
        ),
    ]
